// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertDistanceUnit(arg1, arg2) {
  return window['go']['main']['App']['ConvertDistanceUnit'](arg1, arg2);
}

export function ConvertDmmToDms(arg1) {
  return window['go']['main']['App']['ConvertDmmToDms'](arg1);
}

export function ConvertDmmToEcef(arg1) {
  return window['go']['main']['App']['ConvertDmmToEcef'](arg1);
}

export function ConvertDmmToGeo(arg1) {
  return window['go']['main']['App']['ConvertDmmToGeo'](arg1);
}

export function ConvertDmsToDmm(arg1) {
  return window['go']['main']['App']['ConvertDmsToDmm'](arg1);
}

export function ConvertDmsToEcef(arg1) {
  return window['go']['main']['App']['ConvertDmsToEcef'](arg1);
}

export function ConvertDmsToGeo(arg1) {
  return window['go']['main']['App']['ConvertDmsToGeo'](arg1);
}

export function ConvertECEFToGeo(arg1) {
  return window['go']['main']['App']['ConvertECEFToGeo'](arg1);
}

export function ConvertEcefToDmm(arg1) {
  return window['go']['main']['App']['ConvertEcefToDmm'](arg1);
}

export function ConvertEcefToDms(arg1) {
  return window['go']['main']['App']['ConvertEcefToDms'](arg1);
}

export function ConvertGeoToDmm(arg1) {
  return window['go']['main']['App']['ConvertGeoToDmm'](arg1);
}

export function ConvertGeoToDms(arg1) {
  return window['go']['main']['App']['ConvertGeoToDms'](arg1);
}

export function ConvertGeoToECEF(arg1) {
  return window['go']['main']['App']['ConvertGeoToECEF'](arg1);
}
