// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateAzimuth(arg1:main.Geo,arg2:main.Geo):Promise<number>;

export function CalculateAzimuthAndElevation(arg1:main.Geo,arg2:main.Geo):Promise<main.Angle>;

export function ConvertDistanceUnit(arg1:number,arg2:string):Promise<main.UnitValue>;

export function ConvertDmmToDms(arg1:main.Dmm):Promise<main.Dms>;

export function ConvertDmmToEcef(arg1:main.Dmm):Promise<main.ECEF>;

export function ConvertDmmToGeo(arg1:main.Dmm):Promise<main.Geo>;

export function ConvertDmsToDmm(arg1:main.Dms):Promise<main.Dmm>;

export function ConvertDmsToEcef(arg1:main.Dms):Promise<main.ECEF>;

export function ConvertDmsToGeo(arg1:main.Dms):Promise<main.Geo>;

export function ConvertECEFToGeo(arg1:main.ECEF):Promise<main.Geo>;

export function ConvertEcefToDmm(arg1:main.ECEF):Promise<main.Dmm>;

export function ConvertEcefToDms(arg1:main.ECEF):Promise<main.Dms>;

export function ConvertGeoToDmm(arg1:main.Geo):Promise<main.Dmm>;

export function ConvertGeoToDms(arg1:main.Geo):Promise<main.Dms>;

export function ConvertGeoToECEF(arg1:main.Geo):Promise<main.ECEF>;

export function DistanceBetweenTwoPoints(arg1:main.Geo,arg2:main.Geo):Promise<number>;

export function MoveToLocation(arg1:main.Geo,arg2:number,arg3:number,arg4:number):Promise<main.DmmFoot>;
